// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // Import global styles

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Product Catalog",
  description: "Browse our amazing products",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header
          style={{
            padding: "1rem",
            backgroundColor: "#eee",
            marginBottom: "1rem",
          }}
        >
          <h1>Product Catalog</h1>
          {/* Add Navigation Links here if needed */}
        </header>
        <main>{children}</main>
        <footer
          style={{
            padding: "1rem",
            backgroundColor: "#eee",
            marginTop: "2rem",
            textAlign: "center",
          }}
        >
          <p>© {new Date().getFullYear()} My Store</p>
        </footer>
      </body>
    </html>
  );
}
